# Generated by Django 4.2.1 on 2025-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_account_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
