# Generated by Django 4.2.1 on 2025-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_photogallery_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['-date'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='фссўгтеы/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/photos/', verbose_name='Фото блюда'),
        ),
    ]
