# Generated by Django 4.2.1 on 2025-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_alter_menu_options_alter_photogallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/photos/', verbose_name='Фото'),
        ),
    ]
