# Generated by Django 4.2.1 on 2025-05-30 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0007_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTypeOfDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.typeofdish', verbose_name='Виды блюд, которые должен готовить')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_dish_types', to='specialists.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Связь должностей и блюд',
                'verbose_name_plural': 'Связи должностей и блюд',
            },
        ),
    ]
